apiVersion: v1
kind: Pod
metadata:
  name: init-demo-pod-1
spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  initContainers:
    - name: fetch-from-s3
      image: amazon/aws-cli
      env:
       - name: AWS_ACCESS_KEY_ID
         value: ""
       - name: AWS_SECRET_ACCESS_KEY
         value: ""
       - name: AWS_DEFAULT_REGION
         value: "us-east-1"
      command: ["sh", "-c"]
      args:
        - |
          aws s3 cp s3://harshal-init-container-project/index.html  /data/index.html
      volumeMounts:
        - name: shared-data
          mountPath: /data

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80