apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-required
  namespace: default
  labels: 
    app: myapp
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: myapp
  template:
    metadata: 
      labels: 
        app: myapp
    spec: 
      affinity:                                            # This is the parent section where you define affinity and anti-affinity rules.
        nodeAffinity:                                      # This specifies that the rules apply to node labels.
          requiredDuringSchedulingIgnoreDuringExecution:   # The Pod must be scheduled on a matching node, but if the node's labels change after scheduling, the running Pod is not evicted.
            nodeSelectorTerms:                             # entry contains one or more conditions that can match a node.
            - matchExpressions:                            # This is where you define one or more matching rules.( one and more can define)
              - key: color
                operator: In                               # The In operator means: The node's label value must be one of the values listed below.
                values:
                - blue
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - contanierPort: 80        

# kubectl labels node worker-node color=blue

# kubectl apply -f required-affinity.yml