apiVersion: v1            # tells kubernetes which api group and version to use for secource creating
kind: pod                 # telling kubernetes "what object this yaml defines"
metadata:                 # key part of every resource object, its contain info that uniquely identifies
  name: myapp             # unique name for the resource 
  labels:                 # key-value pairs used to categorize, used by selector 
    app: webapp           # this label says that the object belongs to the application 
    type: frontend
spec:                     # define the desire state or behaviour
  containers:             # 
  - name: my-app          # this is the name of container
    image: nginx


---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: batch/v1
kind: job
metadata:
  name: hello
spec:
  template:
    spec: 
      containers:
      - name: hello
        image: busybox:1.28
        command: ['sh', '-c', 'echo "hello, kubernetes!" && sleep 3600']
      restartPolicy: OnFailure

---

apiVersion: app/v1
kind: Deployment
metadata:
     name: mongodb-dpl
     labels:
       app: mongodb-app
spec: 
    replicas: 3
    selector:
      matchLabels:
        app: mongodb-app
    template: 
      metadata: 
        labels:
          app: mongodb-app
      spec: 
        containers:
        - name: mongodb
          image: nginx
          ports:
          - containerPort: 80
  
---

apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.42.3
        ports:
        - containerPort: 80           
    
---

apiVersion: app/v1
kind: Deployment
metadata:
  name: http
  labels:
    app: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels: 
        app: http
    spec:
      containers:
      - name: http
        image: http
        ports:
        -containerPort: 80
 