apiVersion: apps/v1
kind: Deployment
metadata:
  name: Anti-Affinity
spec:
  replicas: 2
  selector:
    matchlabels:
      app: Anti-Affinity
  template:
    metadata:
      labels:
        app: Anti-Affinity
    spec:
      affinity:
        podAntiAffinity:
          requoredDuringSchedulingignoreDuringExecurtion:
          - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - Anti-Affinity
          topologyKey: "kubernetes.io/hostname"              
        containers:
        - name: nginx
          image: nginx   