apiVersion: apps/v1
kind: Deployment
metadata:
  name: Anti-Affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Anti-Affinity
  template:
    metadata:
      labels:
        app: Anti-Affinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - anti-affinity-app
            topologyKey: "kubernetes.io/hostname"

      containers:
      - name: nginx
        image: nginx   